credential_secret: ###PASSWORD###
theme: default
http_node:
  username: ###USER###
  password: ###PASSWORD###
http_static:
  username: ''
  password: ''
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
system_packages: []
npm_packages:
  - binary-parser
init_commands: []
